# Generated by Django 5.1 on 2024-10-08 05:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to=accounts.models.UserAccount.upload_to),
        ),
    ]
