# Generated by Django 5.1 on 2024-10-14 12:50

import django.db.models.deletion
import medicine_reminder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('interval', 'Interval-based'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='interval', max_length=10)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_type', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('reminder_time', models.TimeField()),
                ('day_of_week', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_reminder', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(default='medicine_reminders/default.jpg', upload_to=medicine_reminder.models.Reminder.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_taken', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_reminder.reminder')),
            ],
        ),
    ]
